# .streamlit/config.toml

[theme]
base = "light" # Ou "dark" - este é o tema base do Streamlit
primaryColor = "#FF4B4B" # Seus estilos CSS podem referenciar ou complementar esta cor
# backgroundColor = ... (você está controlando isso via CSS agora)
# secondaryBackgroundColor = ...
# textColor = ...
font = "sans serif"

[client]
caching = true # Habilita o cache do Streamlit
displayEnabled = true # Habilita o modo de exibição
showSidebar = false # Exibe a barra lateral
showBanner = false # Exibe o banner do Streamlit
showHeader = false # Exibe o cabeçalho do Streamlit
showFooter = false # Exibe o rodapé do Streamlit
toolbarMode = "minimal" # Esconde "Deploy app", etc. na barra lateral
showSidebarNavigation = false #Esconde as páginas na sidebar, encontrado na documentação em: https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[logger]
level = "INFO"

[runner]
gatherUsageStats = false


[UI]
# Configurações de UI adicionais podem ser adicionadas aqui, se necessário
showSidebarNavigation = true   # Esconde a navegação da barra lateral
